---
# Source: api-mock/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
    name: api-mock-release
    labels:
        app.kubernetes.io/name: api-mock
        helm.sh/chart: api-mock-chat
        app.kubernetes.io/instance: api-mock-release
        app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
      nodePort: 30001
  selector:
    app: api-mock
---
# Source: api-mock/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-mock-release
  labels:
    app.kubernetes.io/name: api-mock
    helm.sh/chart: api-mock-chat
    app.kubernetes.io/instance: api-mock-release
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-mock
      release: api-mock-release
  template:
    metadata:
      labels:
        app: api-mock
        release: api-mock-release
    spec:
      containers:
        - name: api-mock
          image: "api-mock:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
