---
# Source: store/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: store-release
  labels:
    app.kubernetes.io/name: store
    helm.sh/chart: store-chat
    app.kubernetes.io/instance: store-release
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
      nodePort: 30002
  selector:
    app: store
---
# Source: store/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: store-release
    labels:
        app.kubernetes.io/name: store
        helm.sh/chart: store-chat
        app.kubernetes.io/instance: store-release
        app.kubernetes.io/managed-by: Helm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: store
      release: store-release
  template:
    metadata:
        labels:
          app: store
          release: store-release
    spec:
      containers:
        - name: store
          image: "store:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          startupProbe:
            failureThreshold: 12
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            httpGet:
              port: http
              path: /actuator/health/readiness
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 20
            timeoutSeconds: 10
            httpGet:
              port: http
              path: /actuator/health/liveness
          readinessProbe:
            failureThreshold: 2
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            httpGet:
              port: http
              path: /actuator/health/readiness
