apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ include "store.fullname" . }}
    labels:
        app.kubernetes.io/name: {{ include "store.name" . }}
        helm.sh/chart: {{ include "store.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "store.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
        labels:
          app: {{ include "store.name" . }}
          release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 5000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          startupProbe:
            failureThreshold: 12
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            httpGet:
              port: http
              path: /actuator/health/readiness
          livenessProbe:
            failureThreshold: 3
            initialDelaySeconds: 0
            periodSeconds: 20
            timeoutSeconds: 10
            httpGet:
              port: http
              path: /actuator/health/liveness
          readinessProbe:
            failureThreshold: 2
            initialDelaySeconds: 0
            periodSeconds: 10
            timeoutSeconds: 5
            httpGet:
              port: http
              path: /actuator/health/readiness

