apiVersion: v1
kind: Service
metadata:
  name: {{ include "store.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "store.name" . }}
    helm.sh/chart: {{ include "store.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      protocol: TCP
      name: http
      nodePort: 30002
  selector:
    app: {{ include "store.name" . }}
