apiVersion: v1
kind: Service
metadata:
    name: {{ include "json-server.fullname" . }}
    labels:
        app.kubernetes.io/name: {{ include "json-server.name" . }}
        helm.sh/chart: {{ include "json-server.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
      nodePort: 30003
  selector:
    app: {{ include "json-server.name" . }}