apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
type: Opaque
data:
  # TODO I need to review it
  admin-user: YWRtaW4=             # base64 de "admin"
  admin-password: cGFzc3dvcmQ=     # base64 de "password"
